### ISSUE TITLE
Using database instead of files

### ISSUE THREAD

**Issue by Ahn1** [owncloud-archive/windows-phone#7]
Hey @framedynamic ,

i want to suggest to use a database for storing the account data. We could use the SQLCE class "CalendarDataContext". (Maybe rename it to "OwncloudDataContext").

A database should be faster and more comfortable because we don't have to serialize the complete data every time.

So we have all data at one place (except the synced files)

**Comment by framedynamic** [comment]
I don't think that DB-Mapping is faster than a serialization of a simple object like account data. Of course sequential loading of serialized objects would be slower but theoretically we don't have to do.

But I agree with merging the data storage as its cleaner. Will do that in next commit.

Furthermore rename the class DBEntity to Entity because there is no DB-bounding and it could be used by the model classes too?

**Comment by Ahn1** [comment]
Yes, ok. 

It would make sense, to rename it to "Entity"
